export const mockData = {
    lastUpdated: new Date().toISOString(),

    // ── Summary Stats ──────────────────────────────────────────────
    summaryStats: {
        activeDisruptions: 7,
        highRiskCorridors: 4,
        exportOpportunities: 5,
        inflationImpact: "+0.6%",
    },

    // ── Active Alerts ──────────────────────────────────────────────
    activeAlerts: [
        {
            id: "A1",
            title: "Red Sea Military Conflict — Shipping Under Threat",
            summary: "Houthi militant attacks in the Red Sea are forcing global oil tankers and cargo vessels to reroute, sharply raising freight costs.",
            description: "Ongoing Houthi militant attacks on commercial and military vessels in the Red Sea have prompted major shipping lines to divert around Africa's Cape of Good Hope. This adds 10–14 days of transit time and increases insurance premiums by up to 400%. India, which imports over 85% of its crude oil, faces immediate pressure on petroleum procurement costs and downstream energy pricing. Fertilizer raw materials (potash and ammonia) are also affected, putting pressure on India's agricultural input supply chain.",
            severity: "HIGH",
            location: "Red Sea, Bab-el-Mandeb Strait",
            category: "Maritime",
            categoryIcon: "🌊",
            impactAreas: ["Petroleum", "Fertilizers", "Energy Costs"],
            indiaImpact: [
                { sector: "Petroleum Imports", type: "IMPORT", effect: "Crude oil costs rising — expect pump price hike of ₹3–5/litre within 30 days." },
                { sector: "Fertilizers", type: "IMPORT", effect: "Potash and ammonia imports delayed; could affect rabi crop input availability." },
            ],
            recommendedAction: "Monitor petroleum reserves & activate alternative supplier dialogue",
            ticker: "🚨 Red Sea Corridor: HIGH RISK — Petroleum & fertilizer imports affected, costs rising",
            timestamp: new Date(Date.now() - 7200000).toISOString(),
        },
        {
            id: "A2",
            title: "Russia-Ukraine Conflict Disrupting Grain & Fertilizer Supply",
            summary: "Ongoing conflict in Eastern Europe continues to squeeze global fertilizer markets and grain availability affecting Indian agri-inputs.",
            description: "The extended Russia-Ukraine conflict has significantly disrupted the global supply of wheat, sunflower oil, and critical fertilizer components. Russia is the world's largest exporter of nitrogen fertilizers, and Ukraine is a major source of potash and ammonium nitrate. India's fertilizer import costs have risen 30% year-on-year, directly squeezing margins for domestic fertilizer producers and raising the government's fertilizer subsidy burden. Global grain price volatility also risks inflationary pressure on India's food basket.",
            severity: "HIGH",
            location: "Eastern Europe, Black Sea",
            category: "Land",
            categoryIcon: "🛤️",
            impactAreas: ["Fertilizers", "Wheat", "Energy"],
            indiaImpact: [
                { sector: "Fertilizer Imports", type: "IMPORT", effect: "Urea and DAP costs up 28–35% year-on-year; widening government subsidy gap." },
                { sector: "Food Inflation", type: "DOMESTIC", effect: "Global wheat price spike risks secondary food inflation of 0.4–0.8% within 2 quarters." },
            ],
            recommendedAction: "Accelerate indigenous fertilizer production & diversify to African suppliers",
            ticker: "🚨 Russia-Ukraine Conflict — Fertilizer & grain supply under pressure, food inflation risk",
            timestamp: new Date(Date.now() - 14400000).toISOString(),
        },
        {
            id: "A3",
            title: "Taiwan Strait Tensions Threaten Semiconductor Supply",
            summary: "Heightened military posturing near Taiwan threatens the global semiconductor supply chain that India's electronics sector depends on.",
            description: "Increased military exercises and naval activity by China near the Taiwan Strait have raised global alarm over semiconductor supply security. Taiwan produces over 60% of the world's logic chips and 90% of the most advanced processors. India's growing electronics manufacturing sector, mobile phone assembly hubs, and EV battery control unit production are heavily dependent on Taiwanese and South Korean semiconductor supply. Prolonged tension could stall India's PLI-backed electronics ambitions and raise consumer electronics prices.",
            severity: "MODERATE",
            location: "Taiwan Strait, East Asia",
            category: "Political",
            categoryIcon: "🏛️",
            impactAreas: ["Electronics", "Semiconductors", "EV Components"],
            indiaImpact: [
                { sector: "Electronics Imports", type: "IMPORT", effect: "Smartphone and laptop component costs could rise 8–15% if access to TSMC output is disrupted." },
                { sector: "EV Manufacturing", type: "DOMESTIC", effect: "Battery management system chips could face 6–10 week lead time extension." },
            ],
            recommendedAction: "Fast-track domestic semiconductor fab investments under India Semiconductor Mission",
            ticker: "⚠️ Taiwan Strait Tensions — Electronics & semiconductor imports at moderate risk",
            timestamp: new Date(Date.now() - 21600000).toISOString(),
        },
        {
            id: "A4",
            title: "EU Pharmaceutical Demand Surge — India Export Window",
            summary: "Europe's dependency on Chinese active pharmaceutical ingredients (APIs) is declining, opening a major export opportunity for Indian pharma companies.",
            description: "The European Medicines Agency and multiple EU health ministries have issued strategic directives to reduce reliance on Chinese Active Pharmaceutical Ingredients (APIs) following supply disruptions in 2023–2025. India, which is the world's largest manufacturer of generic medicines and a major API producer, stands to benefit enormously. Indian pharma exports to the EU have already grown 18% YoY and this trend is expected to accelerate. Companies in Hyderabad, Ahmedabad, and Baddi are reporting record order enquiries from European distributors.",
            severity: "OPPORTUNITY",
            location: "European Union",
            category: "Political",
            categoryIcon: "🏛️",
            impactAreas: ["Pharmaceuticals", "API Chemicals", "Medical Devices"],
            indiaImpact: [
                { sector: "Pharmaceutical Exports", type: "EXPORT", effect: "Estimated additional $2.4B export revenue opportunity over the next 18 months." },
                { sector: "API Manufacturing", type: "EXPORT", effect: "Bulk API demand from EU buyers up 22% — capacity expansion needed at existing plants." },
            ],
            recommendedAction: "Expand EU-compliant pharma production capacity & target bulk API contracts",
            ticker: "✅ EU Pharma Demand Surge — High export opportunity for Indian pharmaceutical manufacturers",
            timestamp: new Date(Date.now() - 28800000).toISOString(),
        },
        {
            id: "A5",
            title: "Suez Canal Congestion — Shipping Timelines Extended",
            summary: "Vessel congestion and rerouting around the Suez Canal is extending India-Europe maritime shipping times by 10–14 days.",
            description: "A combination of security fears in the adjacent Red Sea and increased global cargo volumes has caused significant congestion at the Suez Canal. Many vessels are now choosing the longer Cape of Good Hope route proactively, which adds significant time and fuel costs. For India, this directly delays imports of European-manufactured machine tools, automotive components, and specialty chemicals. Indian exporters shipping textiles, processed food, and engineering goods to Europe are also experiencing delivery delays, potentially triggering contract penalties.",
            severity: "MODERATE",
            location: "Suez Canal, Egypt",
            category: "Maritime",
            categoryIcon: "🌊",
            impactAreas: ["Shipping", "Automotive Parts", "Textiles", "Machine Tools"],
            indiaImpact: [
                { sector: "Capital Goods Imports", type: "IMPORT", effect: "CNC machines and precision tooling imports from Germany & Italy delayed 2–3 weeks." },
                { sector: "Textile Exports to EU", type: "EXPORT", effect: "Delivery lead times to European buyers extended; potential for penalty clauses." },
            ],
            recommendedAction: "Review export contracts for force majeure clauses & switch to air freight for urgent shipments",
            ticker: "⚠️ Suez Canal Congestion — India-Europe shipping timelines extended by 10–14 days",
            timestamp: new Date(Date.now() - 36000000).toISOString(),
        },
    ],

    // ── Import Sector Risks ───────────────────────────────────────
    importRisks: [
        {
            id: "IR1",
            sector: "Petroleum & Energy",
            icon: "⛽",
            level: "HIGH",
            note: "Red Sea tensions pushing crude procurement costs up 12% this quarter.",
        },
        {
            id: "IR2",
            sector: "Electronic Goods",
            icon: "📱",
            level: "MODERATE",
            note: "Suez rerouting adding 2 weeks to semiconductor shipment lead times.",
        },
        {
            id: "IR3",
            sector: "Fertilizers",
            icon: "🌾",
            level: "MODERATE",
            note: "Potash and urea supply under pressure due to Belarus export restrictions.",
        },
        {
            id: "IR4",
            sector: "Coal",
            icon: "🪨",
            level: "LOW",
            note: "Diversified supplier base cushions exposure to any single corridor risk.",
        },
        {
            id: "IR5",
            sector: "Chemicals",
            icon: "🧪",
            level: "LOW",
            note: "Stable supply with minor EU paperwork delays; no critical shortage anticipated.",
        },
    ],

    // ── Export Opportunities ──────────────────────────────────────
    exportOpportunities: [
        {
            id: "EO1",
            sector: "Pharmaceuticals",
            icon: "💊",
            badge: "HIGH DEMAND",
            badgeLevel: "OPPORTUNITY",
            note: "Europe & US seeking alternatives to Chinese API dependence.",
        },
        {
            id: "EO2",
            sector: "Engineering Goods",
            icon: "⚙️",
            badge: "GROWING",
            badgeLevel: "LOW",
            note: "Infrastructure boom in Southeast Asia and Africa driving order intake.",
        },
        {
            id: "EO3",
            sector: "Gems & Jewellery",
            icon: "💎",
            badge: "STABLE",
            badgeLevel: "GRAY",
            note: "Consistent demand; US dollar strength marginally benefits export realisation.",
        },
        {
            id: "EO4",
            sector: "IT Services",
            icon: "💻",
            badge: "GROWING",
            badgeLevel: "LOW",
            note: "Global digital transformation spending up; Indian firms gaining new contracts.",
        },
    ],

    // ── Detailed Sector Data (used in Sectors page) ──────────────
    sectorRisks: {
        petroleum: {
            id: "petroleum",
            name: "Petroleum",
            icon: "⛽",
            type: "IMPORT",
            level: "HIGH",
            riskScore: 82,
            trend: "increasing",
            keyDependency: "Iraq, Saudi Arabia",
            riskBullets: [
                "India imports over 85% of its crude oil — any global shipping disruption has an immediate domestic impact.",
                "Houthi attacks in the Red Sea have rerouted tankers around Africa, adding 10–14 days to delivery and raising freight costs by up to 400%.",
                "Insurance premiums on crude shipments through the Persian Gulf corridor have tripled since late 2024.",
                "Every $10 rise in global crude price adds roughly ₹5,000 crore to India's monthly import bill.",
            ],
            importSources: [
                { country: "Iraq", share: 25 },
                { country: "Saudi Arabia", share: 20 },
                { country: "UAE", share: 15 },
                { country: "Russia", share: 18 },
                { country: "USA", share: 8 },
            ],
            priceTrend: [
                { month: "Sep", value: 87 },
                { month: "Oct", value: 89 },
                { month: "Nov", value: 92 },
                { month: "Dec", value: 95 },
                { month: "Jan", value: 93 },
                { month: "Feb", value: 98 },
            ],
            trendLabel: "Crude Oil Price ($/barrel)",
            recommendedActions: [
                "Increase strategic petroleum reserve utilisation to buffer short-term supply shocks.",
                "Accelerate renewables: fast-track solar and wind projects to reduce crude dependency.",
                "Negotiate long-term supply contracts with Gulf producers to lock in stable pricing.",
                "Incentivise domestic oil exploration in Rajasthan and offshore blocks.",
            ],
            alternativeSuppliers: ["Russia (discounted crude)", "Guyana", "Canada", "Brazil"],
            relatedAlertIds: ["A1"],
            relatedExports: ["IT Services", "Engineering Goods"],
        },
        electronics: {
            id: "electronics",
            name: "Electronics",
            icon: "📱",
            type: "IMPORT",
            level: "MODERATE",
            riskScore: 58,
            trend: "stable",
            keyDependency: "China, Taiwan",
            riskBullets: [
                "India imports ~70% of its electronic components from China and Taiwan — a dual-source vulnerability.",
                "Taiwan Strait military tensions could interrupt semiconductor supply for India's growing mobile and EV manufacturing sector.",
                "Suez Canal congestion adds 10–14 days to European component shipments, straining PLI-scheme production schedules.",
                "India's Electronics Manufacturing Services (EMS) sector is growing fast but still heavily dependent on imported chips.",
            ],
            importSources: [
                { country: "China", share: 44 },
                { country: "Taiwan", share: 18 },
                { country: "South Korea", share: 12 },
                { country: "USA", share: 10 },
                { country: "Japan", share: 8 },
            ],
            priceTrend: [
                { month: "Sep", value: 62 },
                { month: "Oct", value: 60 },
                { month: "Nov", value: 61 },
                { month: "Dec", value: 64 },
                { month: "Jan", value: 63 },
                { month: "Feb", value: 65 },
            ],
            trendLabel: "Semiconductor Import Cost Index",
            recommendedActions: [
                "Fast-track India Semiconductor Mission approvals to build domestic chip production.",
                "Diversify component sourcing to Vietnam, Malaysia, and South Korea.",
                "Support Indian EMS companies with easier access to import credit for component stockpiling.",
                "Push for technology transfer agreements with Japanese and Korean firms.",
            ],
            alternativeSuppliers: ["Vietnam", "Malaysia", "Mexico", "South Korea"],
            relatedAlertIds: ["A3", "A5"],
            relatedExports: ["Pharmaceuticals", "IT Services"],
        },
        fertilizers: {
            id: "fertilizers",
            name: "Fertilizers",
            icon: "🌾",
            type: "IMPORT",
            level: "MODERATE",
            riskScore: 62,
            trend: "stable",
            keyDependency: "Russia, Belarus, China",
            riskBullets: [
                "India imports 25–30% of its fertilizer needs; key inputs like potash and DAP come from conflict-affected regions.",
                "Russia-Ukraine conflict has disrupted global nitrogen fertilizer supply, raising urea prices by 28–35% year-on-year.",
                "Belarus, a key potash exporter, faces Western sanctions that limit Indian procurement flexibility.",
                "Rising fertilizer import costs widen the government's subsidy burden — directly impacting the fiscal deficit.",
            ],
            importSources: [
                { country: "Russia", share: 28 },
                { country: "Belarus", share: 15 },
                { country: "China", share: 20 },
                { country: "Saudi Arabia", share: 14 },
                { country: "Canada", share: 10 },
            ],
            priceTrend: [
                { month: "Sep", value: 310 },
                { month: "Oct", value: 325 },
                { month: "Nov", value: 340 },
                { month: "Dec", value: 338 },
                { month: "Jan", value: 350 },
                { month: "Feb", value: 360 },
            ],
            trendLabel: "Urea Import Price ($/tonne)",
            recommendedActions: [
                "Scale up domestic urea and phosphate production through PSU fertilizer companies.",
                "Explore bilateral trade with Morocco, Jordan, and Senegal for phosphate supply.",
                "Introduce nano-fertilizers at scale to reduce volume dependency on imported inputs.",
                "Strengthen farmer outreach on efficient fertilizer use to reduce subsidy waste.",
            ],
            alternativeSuppliers: ["Morocco", "Jordan", "Senegal", "Australia"],
            relatedAlertIds: ["A1", "A2"],
            relatedExports: ["Agriculture", "Pharmaceuticals"],
        },
        coal: {
            id: "coal",
            name: "Coal",
            icon: "🪨",
            type: "IMPORT",
            level: "LOW",
            riskScore: 28,
            trend: "stable",
            keyDependency: "Australia, Indonesia",
            riskBullets: [
                "India is the second largest coal producer in the world — import dependency is mainly for coking coal used in steelmaking.",
                "Australia and Indonesia provide well-diversified supply with no current major disruption risks.",
                "Domestic coal production reached a record high in FY2024, reducing the import gap.",
                "Transition to renewables is gradually softening long-term coal import demand.",
            ],
            importSources: [
                { country: "Australia", share: 35 },
                { country: "Indonesia", share: 28 },
                { country: "South Africa", share: 15 },
                { country: "Russia", share: 12 },
                { country: "USA", share: 5 },
            ],
            priceTrend: [
                { month: "Sep", value: 140 },
                { month: "Oct", value: 135 },
                { month: "Nov", value: 130 },
                { month: "Dec", value: 128 },
                { month: "Jan", value: 125 },
                { month: "Feb", value: 127 },
            ],
            trendLabel: "Coking Coal Price ($/tonne)",
            recommendedActions: [
                "Continue expanding domestic coal production to further reduce import dependency.",
                "Accelerate adoption of green steel technology to reduce coking coal requirements.",
                "Sign long-term coking coal supply agreements with Australia and Mozambique.",
                "Invest in coal gasification technologies for cleaner industrial use.",
            ],
            alternativeSuppliers: ["Mozambique", "Canada", "Colombia", "Mongolia"],
            relatedAlertIds: [],
            relatedExports: ["Engineering Goods", "Steel"],
        },
        chemicals: {
            id: "chemicals",
            name: "Chemicals",
            icon: "🧪",
            type: "IMPORT",
            level: "LOW",
            riskScore: 32,
            trend: "stable",
            keyDependency: "China, Germany",
            riskBullets: [
                "India imports specialty chemicals from China and Europe; moderate exposure to trade friction or shipping delays.",
                "EU paperwork compliance changes post-REACH regulation updates have caused some minor delays.",
                "India's own chemical sector is growing — particularly dyes, agrochemicals, and specialty polymers.",
                "No critical shortage is anticipated in the next 90 days across major chemical import categories.",
            ],
            importSources: [
                { country: "China", share: 32 },
                { country: "Germany", share: 18 },
                { country: "USA", share: 15 },
                { country: "South Korea", share: 10 },
                { country: "Netherlands", share: 8 },
            ],
            priceTrend: [
                { month: "Sep", value: 95 },
                { month: "Oct", value: 93 },
                { month: "Nov", value: 94 },
                { month: "Dec", value: 96 },
                { month: "Jan", value: 95 },
                { month: "Feb", value: 97 },
            ],
            trendLabel: "Chemical Import Cost Index",
            recommendedActions: [
                "Ensure all export documentation meets updated EU REACH regulatory standards.",
                "Build inventory buffers for specialty chemicals used in pharmaceutical production.",
                "Support Indian chemical manufacturers to substitute imported specialty chemicals.",
                "Pursue Free Trade Agreements to reduce import duties on key chemical feedstocks.",
            ],
            alternativeSuppliers: ["Japan", "Singapore", "Italy", "Belgium"],
            relatedAlertIds: [],
            relatedExports: ["Pharmaceuticals", "Agrochemicals"],
        },
        pharmaceuticals: {
            id: "pharmaceuticals",
            name: "Pharmaceuticals",
            icon: "💊",
            type: "EXPORT",
            level: "OPPORTUNITY",
            riskScore: 12,
            trend: "positive",
            keyDependency: "EU, USA, Africa",
            riskBullets: [
                "India is the world's largest supplier of generic medicines — the 'Pharmacy of the World'.",
                "EU and US buyers are actively reducing dependence on Chinese API suppliers following post-COVID supply lessons.",
                "Indian pharma exports to EU grew 18% YoY in FY2025; major opportunity to lock in long-term contracts.",
                "Hyderabad, Ahmedabad, and Baddi pharma clusters are reporting record enquiries from European distributors.",
            ],
            importSources: [
                { country: "EU / Europe", share: 30 },
                { country: "USA", share: 28 },
                { country: "Africa", share: 18 },
                { country: "ASEAN", share: 12 },
                { country: "Others", share: 10 },
            ],
            priceTrend: [
                { month: "Sep", value: 22 },
                { month: "Oct", value: 23 },
                { month: "Nov", value: 25 },
                { month: "Dec", value: 26 },
                { month: "Jan", value: 28 },
                { month: "Feb", value: 31 },
            ],
            trendLabel: "Pharma Export Revenue ($B annualised)",
            recommendedActions: [
                "Expand EU GMP-certified manufacturing capacity to capture growing European demand.",
                "Target WHO-prequalified generic drugs for African government tenders.",
                "Scale up API production to reduce India's own dependence on Chinese raw inputs.",
                "Negotiate a fast-track Mutual Recognition Agreement with the EU for drug approvals.",
            ],
            alternativeSuppliers: ["N/A — India is a supplier"],
            relatedAlertIds: ["A4"],
            relatedExports: ["API Chemicals", "Medical Devices"],
        },
        engineering: {
            id: "engineering",
            name: "Engineering Goods",
            icon: "⚙️",
            type: "EXPORT",
            level: "LOW",
            riskScore: 20,
            trend: "positive",
            keyDependency: "USA, Germany, UAE",
            riskBullets: [
                "India's engineering exports have grown 8% YoY driven by infrastructure booms in Africa, Southeast Asia, and the Middle East.",
                "Delays in shipping components from Europe (machine tools) due to Suez congestion could affect production schedules.",
                "Strong demand from Gulf countries for construction equipment and industrial components.",
                "India is positioning as an alternative manufacturing hub for global industrial goods buyers.",
            ],
            importSources: [
                { country: "USA", share: 22 },
                { country: "Germany", share: 18 },
                { country: "UAE", share: 15 },
                { country: "UK", share: 10 },
                { country: "Australia", share: 8 },
            ],
            priceTrend: [
                { month: "Sep", value: 9.1 },
                { month: "Oct", value: 9.4 },
                { month: "Nov", value: 9.7 },
                { month: "Dec", value: 10.0 },
                { month: "Jan", value: 10.3 },
                { month: "Feb", value: 10.8 },
            ],
            trendLabel: "Engineering Exports ($B annualised)",
            recommendedActions: [
                "Create dedicated export hubs in Gujarat and Tamil Nadu for engineering goods.",
                "Participate in Africa and ASEAN trade fairs to build long-term buyer relationships.",
                "Offer competitive credit lines through EXIM Bank for large African infrastructure orders.",
                "Develop Made-in-India branding for precision engineering components.",
            ],
            alternativeSuppliers: ["N/A — India is a supplier"],
            relatedAlertIds: ["A5"],
            relatedExports: ["Machine Tools", "Auto Components"],
        },
        itServices: {
            id: "itServices",
            name: "IT Services",
            icon: "💻",
            type: "EXPORT",
            level: "LOW",
            riskScore: 10,
            trend: "positive",
            keyDependency: "USA, UK, Europe",
            riskBullets: [
                "India's IT services export sector is the most resilient — no physical supply chain exposure to geopolitical disruptions.",
                "Global digital transformation and AI adoption are driving record demand for Indian software services.",
                "Major Indian IT firms (TCS, Infosys, Wipro) are growing their deal pipelines in the US and European markets.",
                "Some exposure to US visa policy changes could affect on-site delivery capability.",
            ],
            importSources: [
                { country: "USA", share: 55 },
                { country: "UK", share: 15 },
                { country: "Europe", share: 14 },
                { country: "APAC", share: 10 },
                { country: "Others", share: 6 },
            ],
            priceTrend: [
                { month: "Sep", value: 193 },
                { month: "Oct", value: 197 },
                { month: "Nov", value: 199 },
                { month: "Dec", value: 204 },
                { month: "Jan", value: 208 },
                { month: "Feb", value: 214 },
            ],
            trendLabel: "IT Export Revenue ($B annualised)",
            recommendedActions: [
                "Expand AI/ML service offerings to capture enterprise AI transformation budgets.",
                "Increase GCC (Global Capability Centres) onboarding to deepen client relationships.",
                "Invest in cybersecurity practices to address EU and US data localisation requirements.",
                "Train 1 million new engineers in cloud and AI to maintain talent supply pipeline.",
            ],
            alternativeSuppliers: ["N/A — India is a supplier"],
            relatedAlertIds: [],
            relatedExports: ["Digital Payments", "Startups"],
        },
    },

    // ── Economic Indicators ───────────────────────────────────────
    economicIndicators: {
        rupeeToUsd: 83.15,
        inflationRate: "4.8%",
        forexReserves: "$615 Billion",
        exportGrowth: "+2.3% YoY",
    },

    // ── Market Position Page Data ─────────────────────────────────
    marketPosition: {

        // Country map data: ISO alpha-3 codes with trade status
        tradeCountries: [
            // Major partners — teal
            { iso: "IRQ", name: "Iraq", status: "MAJOR_PARTNER", volume: "$28.6B", commodities: "Crude Oil", risk: "DISRUPTED" },
            { iso: "SAU", name: "Saudi Arabia", status: "MAJOR_PARTNER", volume: "$42.3B", commodities: "Crude Oil, LPG", risk: "ELEVATED" },
            { iso: "ARE", name: "UAE", status: "MAJOR_PARTNER", volume: "$85.3B", commodities: "Gold, Engines, Oil", risk: "STABLE" },
            { iso: "CHN", name: "China", status: "MAJOR_PARTNER", volume: "$118.5B", commodities: "Electronics, Chemicals", risk: "ELEVATED" },
            { iso: "USA", name: "United States", status: "MAJOR_PARTNER", volume: "$119.5B", commodities: "Pharma, IT, Gems", risk: "STABLE" },
            { iso: "RUS", name: "Russia", status: "MAJOR_PARTNER", volume: "$49.2B", commodities: "Oil, Defence, Coal", risk: "ELEVATED" },
            { iso: "DEU", name: "Germany", status: "MAJOR_PARTNER", volume: "$24.8B", commodities: "Machinery, Chemicals", risk: "STABLE" },
            { iso: "GBR", name: "United Kingdom", status: "MAJOR_PARTNER", volume: "$21.4B", commodities: "Pharma, IT, Gems", risk: "STABLE" },
            { iso: "JPN", name: "Japan", status: "MAJOR_PARTNER", volume: "$17.8B", commodities: "Electronics, Steel", risk: "STABLE" },
            { iso: "AUS", name: "Australia", status: "MAJOR_PARTNER", volume: "$26.2B", commodities: "Coal, Gold, Education", risk: "STABLE" },
            { iso: "SGP", name: "Singapore", status: "MAJOR_PARTNER", volume: "$35.6B", commodities: "Electronics, Oil", risk: "STABLE" },
            { iso: "KOR", name: "South Korea", status: "MAJOR_PARTNER", volume: "$22.4B", commodities: "Electronics, Steel", risk: "STABLE" },
            // Disrupted routes — orange
            { iso: "YEM", name: "Yemen", status: "DISRUPTED", volume: "N/A", commodities: "Transit corridor", risk: "CRITICAL" },
            { iso: "EGY", name: "Egypt", status: "DISRUPTED", volume: "$5.2B", commodities: "Suez transit", risk: "DISRUPTED" },
            // High risk — red
            { iso: "IRN", name: "Iran", status: "HIGH_RISK", volume: "$1.2B", commodities: "Oil (restricted)", risk: "CRITICAL" },
            { iso: "UKR", name: "Ukraine", status: "HIGH_RISK", volume: "$2.4B", commodities: "Fertilizer inputs", risk: "CRITICAL" },
            { iso: "TWN", name: "Taiwan", status: "HIGH_RISK", volume: "$8.5B", commodities: "Semiconductors", risk: "ELEVATED" },
        ],

        // Export Opportunity Cards
        exportOpportunityCards: [
            {
                id: "EOC1",
                flag: "🇪🇺",
                region: "European Union",
                sector: "Pharmaceuticals",
                description: "China API supply cuts have created a procurement gap that Indian generic manufacturers can fill rapidly.",
                potential: "$2.1B",
                badge: "OPPORTUNITY",
                color: "emerald",
            },
            {
                id: "EOC2",
                flag: "🇺🇸",
                region: "United States",
                sector: "Engineering Goods",
                description: "US Infrastructure Investment Act driving demand for heavy machinery, pipes and structural steel from low-cost manufacturers.",
                potential: "$800M",
                badge: "OPPORTUNITY",
                color: "emerald",
            },
            {
                id: "EOC3",
                flag: "🇦🇪",
                region: "Middle East",
                sector: "IT Services",
                description: "Gulf nations' Vision 2030 digital transformation programmes are generating large IT outsourcing contracts.",
                potential: "$1.2B",
                badge: "OPPORTUNITY",
                color: "emerald",
            },
        ],

        // Competitor comparison data
        competitorData: [
            { sector: "Pharma", India: 88, China: 72, Bangladesh: 18, Vietnam: 12 },
            { sector: "IT/Software", India: 92, China: 55, Bangladesh: 8, Vietnam: 10 },
            { sector: "Textiles", India: 58, China: 80, Bangladesh: 74, Vietnam: 68 },
            { sector: "Engineering", India: 62, China: 85, Bangladesh: 20, Vietnam: 35 },
            { sector: "Gems", India: 78, China: 48, Bangladesh: 10, Vietnam: 14 },
        ],

        // Import composition donut
        importComposition: [
            { name: "Petroleum", value: 42, color: "#ef4444" },
            { name: "Electronics", value: 18, color: "#f97316" },
            { name: "Fertilizers", value: 12, color: "#eab308" },
            { name: "Coal", value: 9, color: "#64748b" },
            { name: "Chemicals", value: 8, color: "#8b5cf6" },
            { name: "Others", value: 11, color: "#334155" },
        ],

        // Export composition donut
        exportComposition: [
            { name: "IT Services", value: 30, color: "#0d9488" },
            { name: "Engineering", value: 22, color: "#3b82f6" },
            { name: "Pharmaceuticals", value: 14, color: "#10b981" },
            { name: "Gems & Jewellery", value: 13, color: "#f59e0b" },
            { name: "Textiles", value: 11, color: "#ec4899" },
            { name: "Others", value: 10, color: "#334155" },
        ],
    },
};

